### ISSUE TITLE
Add support of Tartarus Pro

### ISSUE THREAD

**Issue by bkhatkov** [vapula87/Keyboarding-Re-Master#1]
Can we please have new Razer Tartarus Pro supported by the application?

**Comment by mhackett909** [comment]
Hey there bkhatkov. I would love to add support for your Razer Tartarus Pro. In fact, after looking at the Pro it seems that adding support for it will be very easy. Can you please read the documentation in /docs to see how to find the controller name and post it here?

**Comment by bkhatkov** [comment]
Hi,
To be honest I wasn't able to get the name of the controller on my mac using the script due to the error:
java.lang.ClassCastException: class java.lang.String cannot be cast to class [Ljava.lang.Object; (java.lang.String and [Ljava.lang.Object; are in module java.base of loader 'bootstrap')
	at net.java.games.input.OSXHIDDevice.addElements(OSXHIDDevice.java:165)
	at net.java.games.input.OSXHIDDevice.addElements(OSXHIDDevice.java:174)
	at net.java.games.input.OSXHIDDevice.getElements(OSXHIDDevice.java:180)
	at net.java.games.input.OSXEnvironmentPlugin.createControllersFromDevice(OSXEnvironmentPlugin.java:225)
	at net.java.games.input.OSXEnvironmentPlugin.enumerateControllers(OSXEnvironmentPlugin.java:265)
	at net.java.games.input.OSXEnvironmentPlugin.<init>(OSXEnvironmentPlugin.java:135)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:166)
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:404)
	at java.base/java.lang.Class.newInstance(Class.java:591)
	at net.java.games.input.DefaultControllerEnvironment.getControllers(DefaultControllerEnvironment.java:157)
	at com.monkygames.kbmaster.engine.HardwareEngine.getControllers(HardwareEngine.java:472)
	at com.monkygames.kbmaster.util.ScanHardware.scanHardware(ScanHardware.java:46)
	at com.monkygames.kbmaster.util.ScanHardware.<init>(ScanHardware.java:25)
	at com.monkygames.kbmaster.util.ScanHardware.main(ScanHardware.java:178)
Device Name == null


However the info about the device that I have is:
Product ID:	0x0244
  Vendor ID:	0x1532
  Version:	2.00
  Speed:	Up to 12 Mb/s
  Manufacturer:	Razer
  Location ID:	0x14300000 / 8
  Current Available (mA):	500
  Current Required (mA):	500
  Extra Operating Current (mA):	0

There are some details:
+-o Razer Tartarus Pro@14300000  <class AppleUSBDevice, id 0x10000308c, registered, matched, active, busy 0 (4 ms), retain 17>
        {
          "sessionID" = 135239407654480
          "idProduct" = 580
          "iManufacturer" = 1
          "bDeviceClass" = 0
          "bMaxPacketSize0" = 64
          "bcdDevice" = 512
          "iProduct" = 2
          "iSerialNumber" = 0
          "bNumConfigurations" = 1
          "Bus Power Available" = 250
          "USB Address" = 9
          "Built-In" = No
          "locationID" = 338690048
          "bDeviceSubClass" = 0
          "bcdUSB" = 512
          "USB Product Name" = "Razer Tartarus Pro"
          "PortNum" = 3
          "non-removable" = "no"
          "AppleUSBAlternateServiceRegistryID" = 4294979722
          "bDeviceProtocol" = 0
          "IOCFPlugInTypes" = {"9dc7b780-9ec0-11d4-a54f-000a27052861"="IOUSBHostFamily.kext/Contents/PlugIns/IOUSBLib.bundle"}
          "IOPowerManagement" = {"DevicePowerState"=0,"CurrentPowerState"=3,"CapabilityFlags"=65536,"MaxPowerState"=4,"DriverPowerState"=3}
          "kUSBCurrentConfiguration" = 1
          "Device Speed" = 1
          "USB Vendor Name" = "Razer"
          "idVendor" = 5426
          "IOGeneralInterest" = "IOCommand is not serializable"
          "IOClassNameOverride" = "IOUSBDevice"
        }

**Comment by mhackett909** [comment]
Unfortunately I have not done any work on the OSX Environment Plugin. This program currently only runs within the Linux environment. I do plan on adding support for Mac eventually. I apologize for the inconvenience.
